### ISSUE TITLE
最新的代码编译后，镜像拉取有问题

### ISSUE THREAD

**Issue by linkagt** [quanxiang-cloud/quanxiang#45]
configs 文件只修改了，域名和master节点ip；

操作过程如下：
git clone https://github.com/quanxiang-cloud/quanxiang.git
 cd quanxiang
 git checkout main
# 修改configs.yml文件中
关于域名和无法解析时候域名一致，还有master节点IP

#编译
 CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o installApp main.go
编译成功，

# 安装
./installApp start -k ~/.kube/config -i -n lowcode

# 中间件安装成功
# 数据库自动操作成功
# 安装软件有问题，出现镜像拉取有问题
# 进行数据库操作
# 将下面值写入数据库
# 数据库gits（host,ssh, known_hosts）操作

INSERT INTO gits (id, host, token, name, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by, tenant_id, known_hosts, ssh) VALUES 
              ('J2P57lAN', 'qxcr.xyz/', '', 'rsa', 1654857150396, 1654857150396, 0, '', '', '', '', 'WzE5Mi4xNjguMjA4LjNdOjEwMDIyIHNzaC1lZDI1NTE5IEFBQUFDM056YUMxbFpESTFOVEU1QUFBQUlPU0x3eHV6bXNuQ2RmcENoNGFuaUZCVDF2U040UUtUcUFZYlhVdHJHN0k4ClsxOTIuMTY4LjIwOC4zXToxMDAyMiBzc2gtcnNhIEFBQUFCM056YUMxeWMyRUFBQUFEQVFBQkFBQUJBUURFdXVZSW5aQW5wNUJGalV2MWdTVGp4RDJud2J2c2xVSUZGa2Z2TXRNRUs1cVROc0RUUGpWejlVSmZDSldnd2pjcUpkRXZWYVZNZlpMN3dWUlpUMnJreTJDUlJPNnFWdGFPeWpET3pXSzBhb1duc241L2VFdlVFM05SbGpqWk9IK2NQZEhzYkluU0llb1FFU0lBM0pEVllzMklDMndZRzQrMlVyQ3dzT0hwSFllcHVlcys2anhRdEpPa2lCb3krczlEWDFGZzRlREQ0dVFJMmg3azdFYVVydUZBcEJ2bW5TRktzaXhvMThTalcxMm5oSitIbVdXclg4OE5DRkVzKzJsaTRWSEpFb2Jwa1p6Y09NbGVUQVdwVTdQUHE0RFhOc0xpTGRIOEwrWi9COXRYZjYrSVByd0lXakhZaFlLbWhsNXZ0RXVHMU1zOU0rd1FSak1LaEJ0YgpbMTkyLjE2OC4yMDguM106MTAwMjIgZWNkc2Etc2hhMi1uaXN0cDI1NiBBQUFBRTJWalpITmhMWE5vWVRJdGJtbHpkSEF5TlRZQUFBQUlibWx6ZEhBeU5UWUFBQUJCQks3eHVSY0xlN25CcGVaVHNCeStWKzdnU2Z0VHFGM1d6dFRheUFzYXdoekFEU3ZpZXNtNjlmTklwTzZBSHB0TEZ1ZXhUa3U2WnJPWWlZVnB2a1RCTHVJPQo=', 'LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUJsd0FBQUFkemMyZ3RjbgpOaEFBQUFBd0VBQVFBQUFZRUF0VTFjZGJnU1liaTVtZ0FVR25KcW1lK2YrQ2lRWlk4UlUzYkRwNS83TVFSOUNRdG04TGFtCmNwSUpJaU5mUVhwZFYycG9aQnJXaGdQVVRRWlM5YzlJZk5iUE5aZmdFc3Mrd0trR2lPS2N3anNxS21ENVU2L1JUaW1GNTIKTWtDaHNidnluc0lET29URUpwdC85aWJ4REdjTEVNaUp3T1RoY3Uwd3JBWTNKdFl2NTE0ZlE2L1BBamFSNzNaS09YZFd0WQpNRy8rME5mc3FNZTlEMVVzRjBWUjMxLzhZakdmenpmZVdyWW8zNjk0SFNoU2p6T3R2YWllVE5CU1ZEWGhJdXdyZUE2QlhuCmxRRXBNZ05xNCtaYkFQTzlndG95K3ZabjBjRHVSM21oUFNxdXZqOWtrd3Uwb2tKRFhZbXBTaklhTG5iZDd2RjFQNFVPTUIKckh5dktDbWY1bGM0bkVacFBuRER0ek5RRkZOdWZPWFdyR0pkMFp5VWZ5VnZCYUgybFFDVHVOOEhmYWw2VGREd2lUT3pXbwpsQ1U4MEZQYlpJeUFLaEFNRzlwYjVJK3NCblgxZEVXdlBjMnZobFBLSWlnWnNlSXBVK0VzMi9sRlpaRFF5eFpFTFdKaEZFCkM2bmtqanoyNnhWbjZrZVBrZUhTREFjQTc0VXJ4b3grbWN2N1BGZmJBQUFGa0YxSUg4cGRTQi9LQUFBQUIzTnphQzF5YzIKRUFBQUdCQUxWTlhIVzRFbUc0dVpvQUZCcHlhcG52bi9nb2tHV1BFVk4ydzZlZit6RUVmUWtMWnZDMnBuS1NDU0lqWDBGNgpYVmRxYUdRYTFvWUQxRTBHVXZYUFNIeld6eldYNEJMTFBzQ3BCb2ppbk1JN0tpcGcrVk92MFU0cGhlZGpKQW9iRzc4cDdDCkF6cUV4Q2FiZi9ZbThReG5DeERJaWNEazRYTHRNS3dHTnliV0wrZGVIME92endJMmtlOTJTamwzVnJXREJ2L3REWDdLakgKdlE5VkxCZEZVZDlmL0dJeG44ODMzbHEyS04rdmVCMG9Vbzh6cmIyb25relFVbFExNFNMc0szZ09nVjU1VUJLVElEYXVQbQpXd0R6dllMYU12cjJaOUhBN2tkNW9UMHFycjQvWkpNTHRLSkNRMTJKcVVveUdpNTIzZTd4ZFQrRkRqQWF4OHJ5Z3BuK1pYCk9KeEdhVDV3dzdjelVCUlRibnpsMXF4aVhkR2NsSDhsYndXaDlwVUFrN2pmQjMycGVrM1E4SWt6czFxSlFsUE5CVDIyU00KZ0NvUURCdmFXK1NQckFaMTlYUkZyejNOcjRaVHlpSW9HYkhpS1ZQaExOdjVSV1dRME1zV1JDMWlZUlJBdXA1STQ4OXVzVgpaK3BIajVIaDBnd0hBTytGSzhhTWZwbkwrenhYMndBQUFBTUJBQUVBQUFHQUN3S2p0dEp5NjFSWWtTMm9DdU1mN2pGTE9iCnJjNmc0Q00xdG5EbXI4eWtGSGhxRVdvMCswVkFqaVhSeGcwSTBwMWdFMFRjQURmeWdFWUprZHVLZlo4eHJvZ295eW92R00KNGc1aHd6WmY1cnZKRjhIRDRuMHU3TnhBc1lpbnk2VlJ6ZzR4dE5MdVNaTk84RW1tSkxDVUhJdmtBdmZYTm83WjNSOHVCOQp3UElJL3JnTWxnTzdRcHNseWJFWldOd1NlL3QxRlYzRUVBc2s5Ty8vdGdMaG1ibTBFdEJwbVU1dlN4b0RpbnlzM1JNWlFkClQyMElCQmlWWkh6U1F5THloVGhxWVNzMERkSG54Nkx1OHVpOXNzd2Y2VjhwTjd1VDZiRGJvS3hOekpyZFFYZUJ3SEY2TDAKb2gxSG9YU0pycmNCbTk1Q2FkSGQwNXFWZUUrOXQ4UWxjN3ZTcmtxOVREUHhDL2JTRWFRQy9EZXo5RnEvVjM0WUh5VzRiUwpvSjFqU0lYT3lJTmVCYjZvVVB5VktGWFlUVVFndjk3ZUptVGhMTVkwVVNRWTVtUEc2UitMcTVtdSsvaXdBWUpraDdobVZxCjZmUDR2SXJFVGRvVWhWWHpzcHBLN3oxR2JMeGx1TDVjbHZSd0R2bjIyZ2dpV0JaUXJDdWJTa0QrU3d3MDBpVUhZQkFBQUEKd0VEM1IzMzBQUVZFQ0FjVkpsK2VTalBDWExUTHlzYlVOcGN2S3NWL0RQamtVczg0Mm0zOC8yWXNHaURDamIybVJJdEFjWQptQXZEa2xoeW4zRGYxalJreUlHVG5QNWNpVHFDbjlONDNFcXMralNlTVhkU3JYOUxLRTZmZzBsTFBISlMrYzdzM3ptNlU0Cmg0MzUwNEdyMytNeWs1aFcyVjltTDJaZUkzdHk0S3kweVFwdkxpVkF6N2V5QUZvbmM0N1REblJIS2xYMi9pc3lacXRSblIKQVVrVENxRUhjVnFVNmppa0xpVGVhdUlOQWZ0SSt0RGNHYURlaGdGZ1dMcXJVV2p3QUFBTUVBNWVpQ000Y2lvbkl4Z1oxNApUM0doWWpQQjR4R205WmsxalM0NWt5SXpHUWtNb3ExTjVlTGdGS0tzbEZIVzJ1V3RJOElURVg5Ym5NTTFIamxNYitYcjVhCjZzUyttRGZSTnVpNTFyc3hzcWY5em1CNFljZmtyYXRtbEU2QVdiMklGNEZOcU1BUUkrT0pFZm1Tb2c5Umdhc2dXcjY0dWgKT2tXMnpGamZNTTAzT21BL1pwbC9QTE43aEFpUCt3d2xQeXhSQzNySnk3SXJOODk1TDlUWDVJZ0d5eVFkeVBuakdOM1kzdAo4SXFldzVIZUhlSm1xQVQwendjVCs4N1hGa0VXZ2JBQUFBd1FESjRMVkN2Mk9nVXUvZ0RXUFZTbGpwNlRVRkJOZDVscUV5CnVyYmtycHZ5VWNnbVlFaXJjZi80S3JxbEgwb25CRjR3R0NXVGNkZzZtK3MyZjVWSnFmZ29YbFRTZFNSSmVEQUFFZkdzL1YKNUxsbU54ZFZuVlkzeTJaRXFSNXpzNWQ3RDVqam1NMFkzc1NHME5MTWQwVmtSeXVFdmNaRkI4Qm0yNFh2WDNtWUlnc3pWbgp6VXhZS1h1eTVCKzd2TFVGWk9ac0VmTWQxOHFDdkhvQnQrd0lrVnFXdElqNytqZG5JcFlzR2lpdTZObHRMa3MxMyswcnRhCnlCUDFYZTZ0TURTMEVBQUFBV2VtaGxibXhwYm1ScGJtZEFlWFZ1YVdaNUxtTnZiUUVDQXdRRgotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0K');

# 数据库操作dockers(host,user_name,secret,name)

INSERT INTO dockers (id, host, user_name, name_space, secret, name, created_at, updated_at, deleted_at, created_by, updated_by, deleted_by, tenant_id) VALUES ('1', 'qxcr.xyz/', 'qxptest', 'privitetest/', 'ZHU**jie9', 'qxcr', null, null, null, null, null, null, null);

# 重新执行安装指令
./installApp start -k ~/.kube/config -i -n lowcode
自动退出时候
打印
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
quanxiang/pkg.ModifyValuesFile({0xc000547780, 0x31}, {0x7ffefe6b37e7, 0x7}, 0xc0000a7880, 0x0)
        /root/quanxiang/pkg/modifyValues.go:189 +0x1a33
quanxiang/pkg.Start({0x7ffefe6b37ce, 0x12}, {0x7ffefe6b37e7, 0x7}, {0x163ab54, 0x15}, {0x162fe87, 0xc}, {0x162fa39, 0xb}, ...)
        /root/quanxiang/pkg/startInstall.go:97 +0x1377
quanxiang/cmd.Execute.func2(0xc0002dd900?, {0x1629e9e?, 0x5?, 0x5?})
        /root/quanxiang/cmd/InstallApp.go:74 +0x2a5
github.com/spf13/cobra.(*Command).execute(0xc0002dd900, {0xc0000966e0, 0x5, 0x5})
        /root/golang/work/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x22bc920)
        /root/golang/work/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /root/golang/work/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
quanxiang/cmd.Execute()
        /root/quanxiang/cmd/InstallApp.go:96 +0x525
main.main()
        /root/quanxiang/main.go:22 +0x17
# 镜像拉取有问题
![image](https://user-images.githubusercontent.com/38818803/180118559-62f6346a-851a-4e1b-89b4-84e2c3deb44b.png)

**Comment by kevinlee607** [comment]
把镜像的地址贴一下看看

**Comment by linkagt** [comment]
# 拉取有问题的镜像
qxcr.io/lowcode/goalie:v1.1.2
qxcr.io/lowcode/flow:v1.1.2

**Comment by kevinlee607** [comment]
那你改一下工作负载里的镜像tag吧，改成v1.1.1， 比如：
qxcr.io/lowcode/flow:v1.1.2 改成 qxcr.io/lowcode/flow:v1.1.1

**Comment by linkagt** [comment]
能否提供个镜像版本清单，好核对

**Comment by linkagt** [comment]
镜像拉取有问题的清单：
qxcr.io/lowcode/goalie:v1.1.2
qxcr.io/lowcode/permit:v1.1.2
qxcr.io/lowcode/form:v1.1.2
qxcr.io/lowcode/structor:v1.1.2
qxcr.io/lowcode/flow:v1.1.2
qxcr.io/lowcode/fileserver:v1.1.2
qxcr.io/lowcode/dispatcher:v1.1.2
qxcr.io/lowcode/audit:v1.1.2
qxcr.io/lowcode/chaos:v1.1.2
qxcr.io/lowcode/app-center:v1.1.2

麻烦帮核对下那个镜像版本不对

**Comment by linkagt** [comment]
按这个镜像版本修改后，
[qxcr.io/lowcode/goalie:v1.1.1](http://qxcr.io/lowcode/goalie:v1.1.1)
[qxcr.io/lowcode/permit:v1.1.2](http://qxcr.io/lowcode/permit:v1.1.2)
[qxcr.io/lowcode/form:v1.1.2](http://qxcr.io/lowcode/form:v1.1.2)
[qxcr.io/lowcode/structor:v1.1.2](http://qxcr.io/lowcode/structor:v1.1.2)
[qxcr.io/lowcode/flow:v1.1.1](http://qxcr.io/lowcode/flow:v1.1.1)
[qxcr.io/lowcode/fileserver:v1.1.1](http://qxcr.io/lowcode/fileserver:v1.1.1)
[qxcr.io/lowcode/dispatcher:v1.1.1](http://qxcr.io/lowcode/dispatcher:v1.1.1)
[qxcr.io/lowcode/audit:v1.1.1](http://qxcr.io/lowcode/audit:v1.1.1)
[qxcr.io/lowcode/chaos:v1.1.2](http://qxcr.io/lowcode/chaos:v1.1.2)
[qxcr.io/lowcode/appcenter:v1.1.2](http://qxcr.io/lowcode/appcenter:v1.1.2)

在工作负载中，重新创建镜像版本修改的部分：
再执行
./installApp start -k ~/.kube/config -n lowcode
安装脚本执行过程退出
--------->部署implant服务 

panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
quanxiang/pkg.ModifyValuesFile({0xc00035ae00, 0x31}, {0x7fffde4ad7f9, 0x7}, 0xc0005cfc00, 0x0)
        /root/quanxiang/pkg/modifyValues.go:189 +0x1a33
quanxiang/pkg.Start({0x7fffde4ad7e3, 0x12}, {0x7fffde4ad7f9, 0x7}, {0x163ab54, 0x15}, {0x162fe87, 0xc}, {0x162fa39, 0xb}, ...)
        /root/quanxiang/pkg/startInstall.go:97 +0x1377
quanxiang/cmd.Execute.func2(0xc0003ffb80?, {0x1629e9e?, 0x4?, 0x4?})
        /root/quanxiang/cmd/InstallApp.go:74 +0x2a5
github.com/spf13/cobra.(*Command).execute(0xc0003ffb80, {0xc000121b40, 0x4, 0x4})
        /root/golang/work/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x22bc920)
        /root/golang/work/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /root/golang/work/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
quanxiang/cmd.Execute()
        /root/quanxiang/cmd/InstallApp.go:96 +0x525
main.main()
        /root/quanxiang/main.go:22 +0x17

目前安装的容器有
![image](https://user-images.githubusercontent.com/38818803/180165770-0d7787c2-fe7b-4616-bc9d-96b94abdf489.png)

![image](https://user-images.githubusercontent.com/38818803/180165885-fcea6a00-379c-4697-9803-1d01fe51c836.png)
![image](https://user-images.githubusercontent.com/38818803/180165947-25e07360-0e1e-440e-a8d6-382d4884268a.png)
![image](https://user-images.githubusercontent.com/38818803/180166018-240c6833-0107-42e3-be1f-e2945c143b3e.png)

并且form

**Comment by kevinlee607** [comment]
#46
