### ISSUE TITLE
部署报错

### ISSUE THREAD

**Issue by linkagt** [quanxiang-cloud/quanxiang#46]
panic: runtime error: index out of range [0] with length 0
goroutine 1 [running]:
quanxiang/pkg.ModifyValuesFile({0xc000368540, 0x31}, {0x7fffc67067fb, 0x7}, 0xc00011ee00, 0x0)
        /root/quanxiang/pkg/modifyValues.go:189 +0x1a33
quanxiang/pkg.Start({0x7fffc67067e2, 0x12}, {0x7fffc67067fb, 0x7}, {0x1641261, 0x15}, {0x1636584, 0xc}, {0x1636136, 0xb}, ...)
        /root/quanxiang/pkg/startInstall.go:97 +0x1377
quanxiang/cmd.Execute.func2(0xc0002fe280?, {0x16305ba?, 0x5?, 0x5?})
        /root/quanxiang/cmd/InstallApp.go:74 +0x2a5
[github.com/spf13/cobra.(*Command).execute(0xc0002fe280](http://github.com/spf13/cobra.(*Command).execute(0xc0002fe280), {0xc000092870, 0x5, 0x5})
        /root/golang/work/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x663
[github.com/spf13/cobra.(*Command).ExecuteC(0x22c7c80)](http://github.com/spf13/cobra.(*Command).ExecuteC(0x22c7c80))
        /root/golang/work/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
[github.com/spf13/cobra.(*Command).Execute(...)](http://github.com/spf13/cobra.(*Command).Execute(...))
        /root/golang/work/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
quanxiang/cmd.Execute()
        /root/quanxiang/cmd/InstallApp.go:96 +0x525
main.main()
        /root/quanxiang/main.go:22 +0x17

然后还有个问题，咨询你们，回复安装的k8s的版本是1.21.5，然后你们的部署应该是绑定的比较多的和k8s的API，建议作为一个后续开发的话，最好不要去绑定特定的版本，云原生和微服务的核心不应该是这样的方式，不然后续使用运维，会死人的；
然后还遇到一个问题，就是安装openfuntion的时候报错
W0729 11:37:20.378108   13774 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W0729 11:37:20.391079   13774 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W0729 11:37:20.404081   13774 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
Error: rendered manifests contain a resource that already exists. Unable to continue with install: ClusterRole "dapr-operator-admin" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "openfunction": current value is "dapr"; annotation validation error: key "meta.helm.sh/release-namespace" must equal "openfunction": current value is "dapr-system"

然后部署代码又安装一个dapr-system，不是很清楚你们的架构是怎样的，感觉版本说明和文档不说的话，非常难部署跑起来，因为部署文档本身也有问题

**Comment by kevinlee607** [comment]
项目人手短缺，很多东西不能很快跟的上节奏。所以也希望有更多的开源爱好者加入这个项目，同我们一起维护。最新的代码已经commit了。

**Comment by linkagt** [comment]
主要是先部署看下目前的是怎样的，如果参与，可能会有几个人参与



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月29日(周五) 下午3:00
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [quanxiang-cloud/quanxiang] 部署报错 (Issue #46)




 
项目人手短缺，很多东西不能很快跟的上节奏。所以也希望有更多的开源爱好者加入这个项目，同我们一起维护。最新的代码已经commit了。

**Comment by linkagt** [comment]
--------->部署fileserver服务 

Error: Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": Post "https://ingress-nginx-controller-admission.ingress-nginx.svc:443/networking/v1/ingresses?timeout=10s": service "ingress-nginx-controller-admission" not found
--------->fileserver 部署完成，如果出现Error错误请参照检查 



--------->部署fluent-bit服务 

Error: rendered manifests contain a resource that already exists. Unable to continue with install: ClusterRole "fluent-bit" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace" must equal "builder": current value is "lowcode"
--------->fluent-bit 部署完成，如果出现Error错误请参照检查 



--------->部署implant服务 

Error: ClusterRoleBinding.rbac.authorization.k8s.io "implantBinding" is invalid: subjects[0].namespace: Required value
--------->implant 部署完成，如果出现Error错误请参照检查 



--------->部署polyapi服务 

Error: Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": Post "https://ingress-nginx-controller-admission.ingress-nginx.svc:443/networking/v1/ingresses?timeout=10s": service "ingress-nginx-controller-admission" not found
--------->polyapi 部署完成，如果出现Error错误请参照检查 

--------->部署polygate服务 

Error: Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": Post "https://ingress-nginx-controller-admission.ingress-nginx.svc:443/networking/v1/ingresses?timeout=10s": service "ingress-nginx-controller-admission" not found
--------->polygate 部署完成，如果出现Error错误请参照检查 

--------->部署process服务 

--------->process 部署完成，如果出现Error错误请参照检查 

--------->部署qxp-web-home服务 

Error: Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": Post "https://ingress-nginx-controller-admission.ingress-nginx.svc:443/networking/v1/ingresses?timeout=10s": service "ingress-nginx-controller-admission" not found
--------->qxp-web-home 部署完成，如果出现Error错误请参照检查 



--------->部署qxp-web-portal服务 

Error: Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": Post "https://ingress-nginx-controller-admission.ingress-nginx.svc:443/networking/v1/ingresses?timeout=10s": service "ingress-nginx-controller-admission" not found
--------->qxp-web-portal 部署完成，如果出现Error错误请参照检查 

--------->部署qxp-web-vendors服务 

Error: Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": Post "https://ingress-nginx-controller-admission.ingress-nginx.svc:443/networking/v1/ingresses?timeout=10s": service "ingress-nginx-controller-admission" not found
--------->qxp-web-vendors 部署完成，如果出现Error错误请参照检查 



安装过程出现的问题，这些是否是因为没有独立先安装OpenFunction造成的？

**Comment by laosandegudai** [comment]
要是能出个docker-compose就好了，快速部署体验。
