### ISSUE TITLE
函数创建后不自动构建

### ISSUE THREAD

**Issue by lijinghui0531** [quanxiang-cloud/quanxiang#61]
1.我使用安装包安装的全象，手动安装了implant 配置了rbac
2.通过api配置了git、docker信息
3.函数在创建之后可以在git中拿到源码
4.我将源码下载下来之后 go mod tidy  vendor 又推送到git中
5.设置版本号之后没有出现报错 查看faas服务日志也是正常的
6. 查看 implant 服务，他只打印了这些内容
 2022-09-14T09:36:58.202Z	INFO	logger/logger.go:24	init-logger-level	{"level": -1}

 I0914 09:36:58.217764       1 leaderelection.go:248] attempting to acquire leader lease default/faas...

 I0914 09:36:58.229627       1 main.go:166] new leader elected: 9xj4TCU0SsqzsDuHYAPbJA

 I0914 09:37:54.268575       1 main.go:166] new leader elected: Q0d8CE1XToaeZXCe3n6T5Q

7.函数创建状态一直是“未开始”

我需要再做什么调整才能将faas模块用起来呢

**Comment by kevinlee607** [comment]
你拉一下最新的master，如果有兴趣可以自己看deployment/deployment/quanxiang_chat里的faas，implant，builder里的yaml文件。如果不行看的话，就直接卸载重新部署。
master修改了很多bug
