### ISSUE TITLE
安装后，使用过程报错

### ISSUE THREAD

**Issue by linkagt** [quanxiang-cloud/quanxiang#64]
Failed to load resource: the server responded with a status of 400 (Bad Request)
api/v1/search/user?query=%7Bquery%28departmentID%3A%221%22%2Cname%3A%22%22%2Cpage%3A1%2Csize%3A10%29%7Busers%7Bid%2Cphone%2Cposition%2Cemail%2Cname%2CuseStatus%2Cdepartments%7Bid%2Cname%2Cattr%7D%2Cleaders%7Bid%2Cname%2Cattr%7D%7D%2Ctotal%7D%7D:1          Failed to load resource: the server responded with a status of 400 (Bad Request)
chunk-index-4903ac74.js:1 Error
    at T (chunk-http-client-aae260f1.js:1:2646)
    at async ae (chunk-selected-list-e5e83160.js:1:6979)
onError @ chunk-index-4903ac74.js:1
chunk-index-4903ac74.js:1 Error: 审批人未填写
    at chunk-http-client-aae260f1.js:1:1114
(anonymous) @ chunk-index-4903ac74.js:1
api/v1/search/user?query=%7Bquery%28departmentID%3A%221%22%2Cname%3A%22%22%2Cpage%3A1%2Csize%3A10%29%7Busers%7Bid%2Cphone%2Cposition%2Cemail%2Cname%2CuseStatus%2Cdepartments%7Bid%2Cname%2Cattr%7D%2Cleaders%7Bid%2Cname%2Cattr%7D%7D%2Ctotal%7D%7D:1          Failed to load resource: the server responded with a status of 400 (Bad Request)
api/v1/search/user?query=%7Bquery%28departmentID%3A%221%22%2Cname%3A%22%22%2Cpage%3A1%2Csize%3A10%29%7Busers%7Bid%2Cphone%2Cposition%2Cemail%2Cname%2CuseStatus%2Cdepartments%7Bid%2Cname%2Cattr%7D%2Cleaders%7Bid%2Cname%2Cattr%7D%7D%2Ctotal%7D%7D:1          Failed to load resource: the server responded with a status of 400 (Bad Request)
chunk-index-4903ac74.js:1 Error
    at T (chunk-http-client-aae260f1.js:1:2646)
    at async ae (chunk-selected-list-e5e83160.js:1:6979)
onError @ chunk-index-4903ac74.js:1
d @ chunk-index-4903ac74.js:1
(anonymous) @ chunk-index-4903ac74.js:1
DevTools failed to load source map: Could not load content for http://portal.linkagt.com:30118/dist/css/antd.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://vendors.linkagt.com:30118/system@6.10.3/system.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://vendors.linkagt.com:30118/react-is@17.0.1/react-is.production.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by kevinlee607** [comment]
哪个环节报的错误？去看一下search的服务的日志。
