### ISSUE TITLE
快速入门打不开

### ISSUE THREAD

**Issue by edvcc** [quanxiang-cloud/quanxiang#66]
[快速入门页面打不开[](url)](url)
<img width="1503" alt="截屏2023-02-10 09 42 02" src="https://user-images.githubusercontent.com/29826192/217979075-2568e70d-ff61-46d5-81fc-ccf3cd29844c.png">

**Comment by kevinlee607** [comment]
域名过期了，后续我们会上线一个新的文档地址，最近忙其他事情，没有时间弄。

**Comment by kevinlee607** [comment]
new domain https://www.quanxiang.dev
